### ISSUE TITLE
Requires llvmlite

### ISSUE THREAD

**Issue by deeuu** [sigsep/sigsep-mus-previews#4]
Hey,

In a fresh conda environment, `pip install -r requirements.txt` failed.

It seems I need to install [llvmlite](https://github.com/numba/llvmlite) first, e.g.
`conda install -c numba llvmlite`

**Comment by faroit** [comment]
numba and llvmlite should come as a dependency of librosa. Unfortunately they missed shipping the llvmlite wheels in time which is why pip fails

See here: https://github.com/numba/numba/issues/2918

This reminds that I will remove the requirements.txt as I like to move over to pipenv's Pipfiles. We an add a conda environment.yml as well if you like
